backend:
  name: git-gateway
  branch: main   # o master si es tu rama principal

media_folder: "images/uploads"   
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Artículos del Blog"
    folder: "blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
