backend:
  name: github
  repo: crjeffrey007/metatronstudio
  branch: main

media_folder: "images/uploads"   # Carpeta donde se suben las imágenes
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Artículos"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
