backend:
  name: github
  repo: crjeffrey007/metatronstudio   # tu repo correcto
  branch: main
  base_url: https://metatronstudio.com   # sin la barra al final
  auth_endpoint: /callback   # usa /callback en vez de /auth

media_folder: "images/uploads"   # dónde se guardan las imágenes en el repo
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}

