backend:
  name: github
  repo: crjeffrey007/metatronstudio
  branch: main
  auth_scope: "repo"       # Scope permitido por Decap CMS 3.x
  site_domain: "https://metatronstudio.pages.dev"

media_folder: "static/images/uploads"  # Carpeta en tu repo donde se guardan imágenes
public_folder: "/images/uploads"       # Ruta pública accesible desde el sitio

media_library:
  name: github
  backend:
    name: github
    repo: crjeffrey007/metatronstudio
    branch: main

publish_mode: editorial_workflow        # Permite flujo de revisión antes de publicar

collections:
  - name: blog
    label: Blog
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }

# Configuración para Cloudflare Access
# Nota: esto no se aplica directamente en config.yml,
# pero tu /admin/ estará protegido por Cloudflare Access antes de que el CMS cargue.
# Debes configurar la app en Cloudflare Access con:
# - GitHub OAuth Client ID y Client Secret
# - Policy que permita solo tu usuario GitHub o tu correo Gmail
# - Dominio protegido: https://metatronstudio.pages.dev/admin/*


