backend:
  name: github
  repo: crjeffrey007/metatronstudio  # tu repo
  branch: main                        # rama principal
  auth_scope: "read:user user:email"  # permisos de GitHub
  site_domain: "https://metatronstudio.pages.dev"
