backend:
  name: git-gateway
  branch: main   # Usa la rama principal de tu repo (puede ser master o main)

media_folder: "images/uploads"   # Carpeta para subir imágenes
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Artículos del Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
