backend:
  name: git-gateway
  repo: crjeffrey007/metatronstudio # tu repo de GitHub
  branch: main

media_folder: "images/uploads"   # dónde se guardan las imágenes
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Imagen Destacada", name: "thumbnail", widget: "image", required: false }
