backend:
  name: git-gateway
  branch: main # Cambia a "master" si tu repo usa esa rama

media_folder: "images/uploads"   # Carpeta donde se guardan las imágenes en el repo
public_folder: "/images/uploads" # Ruta pública de las imágenes

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}" # usa solo el slug del título
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen destacada", name: "thumbnail", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
