backend:
  name: git-gateway
  branch: main # o "master" si tu repo usa master

media_folder: "images/uploads" # dónde se guardan las imágenes en el repo
public_folder: "/images/uploads" # cómo se referencian en el sitio

collections:
  - name: "posts"
    label: "Artículos"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Contenido", name: "body", widget: "markdown" }
