backend:
  name: github
  repo: crjeffrey007/metatronstudio   # ← cambia por TU usuario/repositorio
  branch: main
  base_url: https://metatronstudio.com/   # tu dominio en GitHub Pages
  auth_endpoint: /auth    # lo usaremos para proxy de login
  
media_folder: "images/uploads"   # dónde se guardan las imágenes en el repo
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}
